project: 
  type: website
  output-dir: docs
  resources: 
    day1.pptx
    day2_tidydata.pptx
    day3_data_lm.pptx
    day3.pptx
    walkingspeed.xlsx
    walkingspeed_msc.xlsx
    walkingspeed_day2.xlsx
    day1.qmd
  title: "R and Statistics"    

execute: 
  freeze: auto

website:
  navbar: 
    title: "Statistics and R in Biology"  
    left:
      - text: "Home"
        icon: fa-home
        href: index.html
      - text: Intro to R for Statistics
        menu:
          - text: NBI PhD Intro to R Day 1
            href: day1.qmd
          - text: NBI PhD Intro to R Day 2/3
            href: day2.qmd
          - text: JIC MSc Workshop (2021/2022)
            href: workshopscript.Rmd
          - text: JIC MSc Plant Growth Example (2025)
            href: day3msc.qmd
          - text: Iris data walkthough
            href: irisScript.qmd
      - text: How many samples do I need?
        menu: 
          - text: Course notes
          - href: sampleSize.qmd
      - text: Statistics notes
        menu:
          - text: Notes on graphing
            href: day3.qmd
          - text: Do not group your data points
            href: dichot.qmd
          - text: Simple alpha and beta diversity simulation
            href: alphabeta.qmd
          - text: Selection bias (Berkson bias) in observational studies
            href: berkson.qmd
          - text: Sampling from clustered data in observational studies
            href: independentclusters.qmd
          - text: Run bigger experiments instead of internal replications
            href: repeats.qmd
      - text: Web-r notebook
        menu: 
          - text: WebR book
            href: webr.qmd
      - text: GIBA experimental design course
        menu: 
          - text: Part 1/2
            href: GIBA-session1.qmd
          - text: Part 3
            href: GIBA-session3.qmd

    right:
      - text: "Contact me"
        icon: fa-envelope-o
        href: mailto:george.savva@quadram.ac.uk       
      - text: "GitHub"
        icon: fa-github
        href: https://github.com/georgemsavva       
        
format:
  html:
    theme: cosmo
    toc: true